### PR TITLE
added prefix, return_str keyword arguments

### PR DESCRIPTION
**Pull request by NightMachinery**

### CODE REVIEW

**Comment by NightMachinery** [comment]
I also find this function useful. Will you accept a PR adding it?
```
import executing
import inspect
from textwrap import dedent

class Source(executing.Source):
    def get_text_with_indentation(self, node):
        result = self.asttokens().get_text(node)
        if '\n' in result:
            result = ' ' * node.first_token.start[1] + result
            result = dedent(result)
        result = result.strip()
        return result

def get_with_source(val):
    callFrame = inspect.currentframe().f_back
    callNode = Source.executing(callFrame).node
    source = Source.for_frame(callFrame)
    return val, source.get_text_with_indentation(callNode.args[0])
```

The difference is that it does not include the results of evaluations in the output string.

**Comment by alexmojaki** [comment]
What's the difference between using `return_str` and `ic.format`?

**Comment by NightMachinery** [comment]
> What's the difference between using `return_str` and `ic.format`?

ic.format doesn’t return the evaluated value, correct?

**Comment by alexmojaki** [comment]
Returning the argument makes sense in the context of debugging with `ic()`, but I'm confused about the use cases here. How do/would you use these functions/features?

**Comment by NightMachinery** [comment]
> Returning the argument makes sense in the context of debugging with `ic()`, but I'm confused about the use cases here. How do/would you use these functions/features?

I want to run a function with different inputs, and automatically record these inputs. Some of the inputs are functions, where their value isn’t human-readable, so I need to get the source code that created them.

**Comment by alexmojaki** [comment]
Can you share actual code?

**Comment by NightMachinery** [comment]
@alexmojaki Actual code, no, but here is an example:
```
def run(*, fn1, fn2):
   ...

def run_and_record(fn1s, fn2s):
  db = []
   for fn1, fn1_src in fns1:
        for fn2, fn2_src in fns2:
                db.append(dict(fn1_src=fn1_src, fn2_src=fn2_src, res=run(fn1=fn1, fn2=fn2)))

  return db
```

```
run_and_record([get_with_source(partial(some_fn, some_arg=10)), get_with_source(some_other_fn)],
 [get_with_source(other_fn), get_with_source(another_fn)])
```

**Comment by alexmojaki** [comment]
I don't think this fits with the main purpose of icecream, which is convenient debugging. We already get plenty of questions from users that could be answered by a closer look at the README, so it doesn't seem worth adding more arguments/functions for such advanced and niche uses.

`executing` and `asttokens` provide the foundation needed to build these kinds of magical functions as you've done already. https://github.com/alexmojaki/sorcery makes it a bit easier and is probably the right place for this kind of thing. In fact it already provides `args_with_source` which seems to match what you need. You could also probably write a spell `run_and_record` that lets you skip `get_with_source` and write:

```python
run_and_record(
  [partial(some_fn, some_arg=10), some_other_fn],
  [other_fn, another_fn],
)
```

The only issue is that indentation in multiline expressions isn't properly handled. It'd be fine in the example above, but not if `partial(some_fn, some_arg=10)` was spread over multiple lines. The best place to make a PR about that might be `asttokens`. Then `executing`, `sorcery`, and `icecream` could all benefit.

Finally, you might also be interested in https://github.com/pwwang/python-varname

**Comment by NightMachinery** [comment]
That makes sense, thanks.

**Pull request closed without merging**
