### PR TITLE
added printLinenumber option

### PR DESCRIPTION
**Pull request by mariku**
I added line output  for output with args.
```python
from icecream import ic                                                                                                       
ic.configureOutput(printLineNumber=True)                                                                                      
                                                                                                                               
def foo(a, b):                                                                                                                
      ic(a, b)                                                                                                                  
      a = 4                                                                                                                     
      ic(a, b)                                                                                                                  
      return a * b                                                                                                                                                                                                                                             
  ic(foo(3, 4))   
```
Prints
```
ic| foo.py:5 - a: 3, b: 4
ic| foo.py:7 - a: 4, b: 4
ic| foo.py:10 - foo(3, 4): 16
```

Thx for your great work. I like it very much.

### CODE REVIEW

**Comment by gruns** [comment]
Wonderful pull request. It would be great to include the filename + line number for argument output!

I want to think a bit more whether `printLineNumber` is the best flag variable name. A more general name, like `includeSourceLocation` or `includeLineNumber`, strikes me as more apt because it's possible nothing might actually be `print`ed if `outputFunction` is specified.

Your idea is wonderful; I just want to think a little bit to make sure we pick the best variable name for the job.

**Comment by mariku** [comment]
Yeah, I agree, we should choice a more general name. 
How about `withSourceLocation`?

**Comment by gruns** [comment]
After rumination, I prefer `includeLineNumber`. It's explicit enough that one can intuit what the flag does without consulting the documentation.

Next question: which single character delimiter should be appended after the new `<source>:<linenumber>` inclusion? Some examples:

```
ic| foo.py:5 a: 3, b: 4
ic| foo.py:7 a: 4, b: 4
ic| foo.py:10 foo(3, 4): 16

ic| foo.py:5 - a: 3, b: 4
ic| foo.py:7 - a: 4, b: 4
ic| foo.py:10 - foo(3, 4): 16

ic| foo.py:5| a: 3, b: 4
ic| foo.py:7| a: 4, b: 4
ic| foo.py:10| foo(3, 4): 16

ic| foo.py:5] a: 3, b: 4
ic| foo.py:7] a: 4, b: 4
ic| foo.py:10] foo(3, 4): 16

ic| foo.py:5: a: 3, b: 4
ic| foo.py:7: a: 4, b: 4
ic| foo.py:10: foo(3, 4): 16

ic| foo.py:5) a: 3, b: 4
ic| foo.py:7) a: 4, b: 4
ic| foo.py:10) foo(3, 4): 16

ic| foo.py:5* a: 3, b: 4
ic| foo.py:7* a: 4, b: 4
ic| foo.py:10* foo(3, 4): 16

ic| foo.py:5$ a: 3, b: 4
ic| foo.py:7$ a: 4, b: 4
ic| foo.py:10$ foo(3, 4): 16

ic| foo.py:5# a: 3, b: 4
ic| foo.py:7# a: 4, b: 4
ic| foo.py:10# foo(3, 4): 16

ic| foo.py:5! a: 3, b: 4
ic| foo.py:7! a: 4, b: 4
ic| foo.py:10! foo(3, 4): 16x

ic| foo.py:5` a: 3, b: 4
ic| foo.py:7` a: 4, b: 4
ic| foo.py:10` foo(3, 4): 16x

ic| foo.py:5&   a: 3, b: 4
ic| foo.py:7&   a: 4, b: 4
ic| foo.py:100& foo(3, 4): 16x

ic| foo.py:5^ a: 3, b: 4
ic| foo.py:7^ a: 4, b: 4
ic| foo.py:100^ foo(3, 4): 16

ic| foo.py:5~ a: 3, b: 4
ic| foo.py:7~ a: 4, b: 4
ic| foo.py:100~ foo(3, 4): 16

ic| foo.py:5- a: 3, b: 4
ic| foo.py:7- a: 4, b: 4
ic| foo.py:100- foo(3, 4): 16

ic| foo.py:5+ a: 3, b: 4
ic| foo.py:7+ a: 4, b: 4
ic| foo.py:100+ foo(3, 4): 16

ic| foo.py:5% a: 3, b: 4
ic| foo.py:7% a: 4, b: 4
ic| foo.py:100% foo(3, 4): 16

ic| foo.py:5/ a: 3, b: 4
ic| foo.py:7/ a: 4, b: 4
ic| foo.py:100/ foo(3, 4): 16

ic| foo.py:5= a: 3, b: 4
ic| foo.py:7= a: 4, b: 4
ic| foo.py:100= foo(3, 4): 16

ic| foo.py:5> a: 3, b: 4
ic| foo.py:7> a: 4, b: 4
ic| foo.py:100> foo(3, 4): 16

ic| foo.py:5. a: 3, b: 4
ic| foo.py:7. a: 4, b: 4
ic| foo.py:100. foo(3, 4): 16

ic| foo.py:5? a: 3, b: 4
ic| foo.py:7? a: 4, b: 4
ic| foo.py:100? foo(3, 4): 16
```

I like the hyphen `-`

```
ic| foo.py:5- a: 3, b: 4
ic| foo.py:7- a: 4, b: 4
ic| foo.py:100- foo(3, 4): 16
```

and plus `+` the most.

```
ic| foo.py:5+ a: 3, b: 4
ic| foo.py:7+ a: 4, b: 4
ic| foo.py:100+ foo(3, 4): 16
```

What do you think?

**Comment by gruns** [comment]
I opted for `inludeContext`, over `inludeLineNumber` in v1.3. The `includeContext` flag adds the filename, line number, and calling function to `ic()`'s output.

```pycon
>>> from icecream import ic
>>>
>>> ic.configureOutput(includeContext=True)
>>> 
>>> def foo():
>>>   ic('str')
>>> foo()
```

Prints

```
ic| example.py:12 in foo()- 'str': 'str'
```

Upgrade with

```
pip install icecream --upgrade
```

Thank you again, @mariku, for your pull request. Don't hesitate to let me know if there's anything else I can do for you.

**Pull request closed without merging**
